export const API_ROUTES = {
  auditStart: "/api/tools/audit/start",
  auditStatus: (id: string) => `/api/tools/audit/status/${id}`,
  auditStatusDelta: (id: string, known: { updatedAt?: string; status?: string; pagesCrawled?: number; issuesFound?: number; hasReport?: boolean }) => {
    const params = new URLSearchParams({ delta: '1' });
    if (known.updatedAt) params.set('knownUpdatedAt', known.updatedAt);
    if (known.status) params.set('knownStatus', known.status);
    if (known.pagesCrawled != null) params.set('knownPagesCrawled', String(known.pagesCrawled));
    if (known.issuesFound != null) params.set('knownIssuesFound', String(known.issuesFound));
    if (known.hasReport) params.set('hasReport', '1');
    return `/api/tools/audit/status/${id}?${params.toString()}`;
  },
  auditResult: (id: string) => `/api/tools/audit/result/${id}`,
  auditHistory: "/api/tools/audits/history",
  auditCompare: (currentId: string, baselineId: string) => `/api/tools/audit/compare/${encodeURIComponent(currentId)}/${encodeURIComponent(baselineId)}`,
  auditEvents: (id: string) => `/api/tools/audit/events/${id}`,
  auditCancel: (id: string) => `/api/tools/audit/cancel/${id}`,
  auditExport: (id: string, format: string) => `/api/tools/audit/export/${id}/${format}`,
  auditRerun: (id: string) => `/api/tools/audit/rerun/${id}`,
  auditArchive: (id: string) => `/api/tools/audit/archive/${id}`,
  auditDelete: (id: string) => `/api/tools/audit/${id}`,
  auditFindingWorkflow: (id: string) => `/api/tools/audit/${encodeURIComponent(id)}/finding-workflow`,
  auditFindingWorkflowItem: (id: string, findingKey: string) => `/api/tools/audit/${encodeURIComponent(id)}/finding-workflow/${encodeURIComponent(findingKey)}`,
  auditShare: (id: string) => `/api/tools/audit/${encodeURIComponent(id)}/share`,
  sharedReport: (token: string) => `/api/tools/shared-reports/${encodeURIComponent(token)}`,
  projectsOverview: '/api/tools/projects/overview',
  projects: '/api/tools/projects',
  project: (id: string) => `/api/tools/projects/${encodeURIComponent(id)}`,
  projectNotifications: '/api/tools/projects/notifications',
  projectNotificationsRead: '/api/tools/projects/notifications/read',
  searchConsoleStatus: '/api/tools/search-console/status',
  searchConsoleConnect: '/api/tools/search-console/connect',
  searchConsoleSync: (propertyId: string) => `/api/tools/search-console/sync/${encodeURIComponent(propertyId)}`,
  searchConsoleData: (propertyId: string) => `/api/tools/search-console/data/${encodeURIComponent(propertyId)}`,
  searchConsoleConnection: '/api/tools/search-console/connection',
  version: '/api/version',
  publicPlans: '/api/tools/plans/public',
  accountExport: '/api/tools/me/export',
  accountDelete: '/api/tools/me/delete',
  adminDiagnostics: '/api/tools/admin/diagnostics',
  meProfile: "/api/tools/me/profile",
  securityStart: "/api/tools/audit/start", // Based on the code, security audit calls /api/tools/audit/start with type="security"
  keywordResearch: "/api/tools/keyword/research",
  websiteAnalyze: "/api/tools/website/analyze",
  domainLinkSignals: "/api/tools/domain/link-signals",
  clusters: "/api/tools/clusters",
  contentBrief: "/api/tools/content-brief",
  competitorGap: "/api/tools/competitor-gap",
  imports: '/api/tools/imports',
  importRows: (id: string) => `/api/tools/imports/${encodeURIComponent(id)}/rows`,
  blogPosts: "/api/tools/blog/posts",
  blogPost: (slug: string) => `/api/tools/blog/posts/${encodeURIComponent(slug)}`,
  adminBlogPosts: "/api/tools/admin/blog/posts",
  adminBlogPost: (id: string) => `/api/tools/admin/blog/posts/${encodeURIComponent(id)}`,
  adminBlogPostWorkflow: (id: string) => `/api/tools/admin/blog/posts/${encodeURIComponent(id)}/workflow`,
  adminBlogSourceInspect: "/api/tools/admin/blog/source/inspect",
  adminBlogPreflight: "/api/tools/admin/blog/preflight",
  adminBlogEditorDraft: "/api/tools/admin/blog/editor-draft",
  adminBlogNotifications: "/api/tools/admin/blog/notifications",
  adminBlogNotificationsRead: "/api/tools/admin/blog/notifications/read",
  adminBlogOverview: "/api/tools/admin/blog/overview",
  adminBlogSettings: "/api/tools/admin/blog/settings",
  adminBlogJobs: "/api/tools/admin/blog/jobs",
  adminBlogJobRetry: (id: string) => `/api/tools/admin/blog/jobs/${encodeURIComponent(id)}/retry`,
  adminBlogBatches: "/api/tools/admin/blog/batches",
  adminBlogImageImport: "/api/tools/admin/blog/images/import",
  adminBlogProviderTest: "/api/tools/admin/blog/provider/test",
  adminBlogProviderDiagnostics: "/api/tools/admin/blog/provider/diagnostics",
  adminBlogSectionRevisions: (id: string) => `/api/tools/admin/blog/posts/${encodeURIComponent(id)}/section-revisions`,
  adminBlogSectionRegeneration: (id: string) => `/api/tools/admin/blog/posts/${encodeURIComponent(id)}/section-regeneration`,
  adminBlogSectionRevisionDecision: (id: string) => `/api/tools/admin/blog/section-revisions/${encodeURIComponent(id)}/decision`,
  adminBlogSources: "/api/tools/admin/blog/sources",
  adminBlogSource: (id: string) => `/api/tools/admin/blog/sources/${encodeURIComponent(id)}`,
  adminBlogSourceTest: (id: string) => `/api/tools/admin/blog/sources/${encodeURIComponent(id)}/test`,
  adminBlogTrendAction: (id: string) => `/api/tools/admin/blog/trends/${encodeURIComponent(id)}/action`,
  adminBlogOperations: "/api/tools/admin/blog/operations",
  adminBlogOperationAction: "/api/tools/admin/blog/operations/action",
};
