import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync('src/components/audit/FindingWorkspace.tsx', 'utf8');
const live = readFileSync('src/components/audit/LiveAuditProgress.tsx', 'utf8');
assert.match(source, /selected \? 'xl:grid-cols-\[minmax\(0,1fr\)_minmax\(390px,470px\)\]' : ''/, 'no inspector column may be reserved while closed');
assert.match(source, /openInspector\(issue/);
assert.match(source, /setSelectedId\(null\)/);
assert.match(source, /PAGE_SIZE = 20/, 'long lists must be paginated');
assert.match(source, /Search URL or finding/);
assert.match(source, /Filter by error type/);
assert.match(source, /min-w-0 overflow-hidden/);
assert.match(source, /fixed inset-x-0 bottom-0 top-\[4\.25rem\]/, 'mobile inspector must use a reachable sheet');
assert.match(source, /xl:sticky/, 'desktop inspector must remain beside the list');
assert.match(source, /overflow-y-auto overscroll-contain/);
assert.match(source, /Implementation note/);
assert.match(source, /Previous/);
assert.match(source, /Next/);
assert.match(live, /<FindingWorkspace/);
assert.doesNotMatch(live, /grid-cols-\[minmax\(0,1\.2fr\)_minmax\(360px,\.8fr\)\]/);
console.log('Findings layout smoke test passed.');
