import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import '../src/lib/security/checks/all-checks';
import { SECURITY_CHECK_REGISTRY } from '../src/lib/security/checks/registry';

const read = (path: string) => readFile(path, 'utf8');
const publicUi = await Promise.all([
  'src/components/LandingPage.tsx',
  'src/components/layout/ProductShells.tsx',
  'src/components/Login.tsx',
  'src/components/Register.tsx',
  'src/components/blog/BlogIndex.tsx',
  'src/components/audit/LiveAuditProgress.tsx',
].map(read)).then((files) => files.join('\n'));

assert.doesNotMatch(publicUi, /unlock|supercharge|game-changing|cutting-edge|all-in-one|seamlessly|effortlessly/i);
assert.doesNotMatch(publicUi, /generated by ai|built with chatgpt|created with ai|gemini generated/i);
assert.doesNotMatch(publicUi, /trusted by|customer logos?|testimonials?|websites audited|rank(?:ing)? increase|traffic growth/i);
assert.match(publicUi, /Example report/);
assert.match(publicUi, /Demonstration data/);
assert.match(publicUi, /deterministic checks/i);
assert.match(publicUi, /AI-assisted drafting/);

const definitions = Object.values(SECURITY_CHECK_REGISTRY);
assert.ok(definitions.length >= 70, 'security finding copy must cover the registered check set');
for (const check of definitions) {
  assert.doesNotMatch(check.description, /^Check for /i, `${check.id} has generated description copy`);
  assert.doesNotMatch(check.recommendation, /^Fix /i, `${check.id} has generated recommendation copy`);
  assert.ok(check.title.length >= 8, `${check.id} needs a useful title`);
  assert.ok(check.description.length >= 35, `${check.id} needs a specific observation`);
  assert.ok(check.recommendation.length >= 35, `${check.id} needs a specific recommendation`);
}

console.log('Product craftsmanship smoke test passed.');
